modLoader="javafml"
loaderVersion="[47,)"
license="CC-BY-NC 4.0"

[[mods]]
modId="citymod"
version="2.1.9"
displayName="CityMod"
mixinConfigs="citymod.mixins.json"
displayURL="https://github.com/lyza-1031/citymod_reborn"
logoFile="logo.png"
authors="Lyza_1031"
description="Use this mod to build better Chinese style city"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.citymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.citymod]]
    modId="architectury"
    mandatory=true
    versionRange="[9.1.10,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.citymod]]
modId="embeddium"
mandatory=false
versionRange="[0.2.0,)"
ordering="NONE"
side="CLIENT"
[[dependencies.citymod]]
modId="modernui"
mandatory=false
versionRange="[0.1.0,)"
ordering="NONE"
side="CLIENT"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration