modLoader="javafml"
loaderVersion="[4,)"
license="CC-BY-NC 4.0"

[[mods]]
modId="citymod"
version="0.2.16.25"
displayName="CityMod"
displayURL="https://space.bilibili.com/493607297"
logoFile="logo.png"
credits="Made by Mcreator"
authors="Lyza_1031"
description="Use this mod to build Better Chinese Style City"

[[dependencies.citymod]]
modId="minecraft"
type="required"
versionRange="[1.21.10,1.21.11]"
ordering="AFTER"
side="BOTH"

[[dependencies.citymod]]
modId="architectury"
type="required"
versionRange="[19.0.1,)"
ordering="AFTER"
side="BOTH"