modLoader="javafml"
loaderVersion="[4,)"
license="CC-BY-NC 4.0"

[[mods]]
modId="citymod"
version="2.2.0"
displayName="CityMod"
displayURL="https://github.com/lyza-1031/citymod_reborn"
logoFile="logo.png"
authors="Lyza_1031"
description="Use this mod to build Better Chinese Style City"

[[dependencies.citymod]]
modId="minecraft"
type="required"
versionRange="[26.1,26.2]"
ordering="AFTER"
side="BOTH"

[[dependencies.citymod]]
modId="architectury"
type="required"
versionRange="[19.0.1,)"
ordering="AFTER"
side="BOTH"